version: 0.2

env:
  variables:
    IMAGE_REPO: "483166811085.dkr.ecr.eu-north-1.amazonaws.com/chullmeri/jenkins-shrutz"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 483166811085.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_REPO:$IMAGE_TAG
artifacts:
  files:
    - appspec.yml
    - scripts/deploy.sh
